version: "3"

services:
  backend:
    build: .
    ports:
      - "3000:8080"
    privileged: false
  
  db:
    build: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=snh
    privileged: false
   
