version: "3"

services:
  backend:
    build: .
    ports:
      - "3000:8080"
    privileged: false
    environment:
      - DEV=1
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_PROJECT_ID=${GMAIL_PROJECT_ID}
      - GMAIL_AUTH_URI=${GMAIL_AUTH_URI}
      - GMAIL_TOKEN_URI=${GMAIL_TOKEN_URI}
      - GMAIL_AUTH_PROVIDER_X509_CERT_URL=${GMAIL_AUTH_PROVIDER_X509_CERT_URL}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
    volumes:
      - ./backend:/var/www/html
      - ./ebooks:/var/www/ebooks

  # frontend:
    # build: frontend
    # ports:
      # - "8080:80"

  db:
    build: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=snh
    ports:
      - 3306:3306
    privileged: false
   
