version: "3"

services:
  backend:
    build: .
    ports:
      - "3000:8080"
    privileged: false
    environment:
      - DEV=1
    volumes:
      - ./backend:/var/www/html
      - ./ebooks:/var/www/ebooks

  # frontend:
    # build: frontend
    # ports:
      # - "8080:80"

  db:
    build: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=snh
    ports:
      - 3306:3306
    privileged: false
   
